development:
  adapter: mysql
  database: picky_dev
  hostname: 127.0.0.1
  username: root
  password:

test:
  adapter: mysql 
  database: picky_test 
  hostname: 127.0.0.1
  username: root
  password:
